import type { Metadata } from "next";
import Image from "next/image";
import { Nav } from "@/components/nav";
import { Footer } from "@/components/footer";
import { getDictionary } from "@/i18n/server";

export const metadata: Metadata = { title: "Brand assets · ReelClip", description: "Official ReelClip logos, app icon, and brand colours for press, partners, and collaborators." };

const COLOUR_SWATCHES = [
  { hex: "#C4EF33", className: "bg-accent" },
  { hex: "#0E0F11", className: "bg-bg" },
  { hex: "#F0F1ED", className: "bg-text" },
  { hex: "#A6ABAB", className: "bg-text-muted" }
] as const;

export default async function BrandPage() {
  const { brand: copy } = await getDictionary();
  return <><Nav /><main>
    <section className="relative overflow-hidden border-b border-hairline px-6 pb-16 pt-16 sm:px-10 sm:pb-24 sm:pt-24"><div className="pointer-events-none absolute inset-0 bg-grid opacity-30" /><div className="relative mx-auto grid max-w-6xl gap-12 lg:grid-cols-[1fr_0.86fr] lg:items-end"><div><div className="mb-5 text-xs font-bold uppercase tracking-[0.2em] text-accent">{copy.eyebrow}</div><h1 className="max-w-xl text-4xl font-black leading-[0.98] tracking-tight sm:text-6xl">{copy.heading}</h1><p className="mt-6 max-w-xl text-base leading-relaxed text-text-muted sm:text-lg">{copy.intro}</p></div><div className="rounded-[2rem] border border-hairline bg-surface p-7 shadow-[inset_0_1px_0_rgba(255,255,255,0.06)] sm:p-10"><div className="relative h-24 w-full sm:h-32"><Image src="/wordmark.png" alt={copy.wordmarkAlt} fill sizes="(max-width: 1024px) 100vw, 32rem" className="object-contain object-left" priority /></div><p className="mt-7 max-w-sm text-sm leading-relaxed text-text-muted">{copy.summary}</p></div></div></section>
    <section className="border-b border-hairline px-6 py-16 sm:px-10 sm:py-20"><div className="mx-auto max-w-6xl"><div className="mb-10 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><div className="mb-3 text-xs font-bold uppercase tracking-[0.2em] text-accent">{copy.logosEyebrow}</div><h2 className="text-3xl font-black tracking-tight sm:text-4xl">{copy.logosHeading}</h2></div><p className="max-w-sm text-sm leading-relaxed text-text-muted">{copy.logosIntro}</p></div><div className="grid gap-5 lg:grid-cols-[1.35fr_0.65fr]"><AssetPanel title={copy.primaryWordmark} detail={copy.primaryWordmarkDetail} href="/wordmark.png" download="reelclip-wordmark.png" buttonLabel={copy.downloadPng}><div className="relative h-32 w-full sm:h-40"><Image src="/wordmark.png" alt={copy.primaryWordmarkAlt} fill sizes="(max-width: 1024px) 100vw, 42rem" className="object-contain object-left" /></div></AssetPanel><AssetPanel title={copy.logoMark} detail={copy.logoMarkDetail} href="/logomark.png" download="reelclip-logo-mark.png" buttonLabel={copy.downloadPng}><div className="relative mx-auto h-40 w-32 sm:h-48 sm:w-40"><Image src="/logomark.png" alt={copy.logoMarkAlt} fill sizes="10rem" className="object-contain" /></div></AssetPanel></div><div className="mt-5 grid gap-5 md:grid-cols-[0.7fr_1.3fr]"><AssetPanel title={copy.appIcon} detail={copy.appIconDetail} href="/app-icon-button.png" download="reelclip-app-icon.png" buttonLabel={copy.downloadPng}><div className="relative mx-auto h-36 w-36 sm:h-40 sm:w-40"><Image src="/app-icon-button.png" alt={copy.appIconAlt} fill sizes="10rem" className="object-contain" /></div></AssetPanel><div className="flex flex-col justify-between rounded-[2rem] border border-hairline bg-surface p-7 shadow-[inset_0_1px_0_rgba(255,255,255,0.06)] sm:p-8"><div><div className="text-xs font-bold uppercase tracking-[0.2em] text-accent">{copy.shortDescription}</div><p className="mt-4 max-w-xl text-xl font-bold leading-snug sm:text-2xl">{copy.shortDescriptionHeading}</p></div><p className="mt-6 max-w-2xl text-sm leading-relaxed text-text-muted">{copy.shortDescriptionBody}</p></div></div></div></section>
    <section className="border-b border-hairline px-6 py-16 sm:px-10 sm:py-20"><div className="mx-auto grid max-w-6xl gap-12 lg:grid-cols-[0.8fr_1.2fr]"><div><div className="mb-3 text-xs font-bold uppercase tracking-[0.2em] text-accent">{copy.colourEyebrow}</div><h2 className="text-3xl font-black tracking-tight sm:text-4xl">{copy.colourHeading}</h2><p className="mt-4 max-w-sm text-sm leading-relaxed text-text-muted">{copy.colourBody}</p></div><div className="grid gap-3 sm:grid-cols-2">{COLOUR_SWATCHES.map((swatch, index) => <div key={swatch.hex} className="flex items-center gap-4 border-b border-hairline py-4 first:pt-0 sm:odd:pr-5 sm:even:pl-5"><span className={`h-12 w-12 shrink-0 rounded-full border border-white/10 ${swatch.className}`} /><div><div className="font-bold">{copy.colours[index]}</div><div className="mt-1 font-mono text-xs text-text-muted">{swatch.hex}</div></div></div>)}</div></div></section>
    <section className="px-6 py-16 sm:px-10 sm:py-20"><div className="mx-auto max-w-6xl"><div className="mb-10 max-w-2xl"><div className="mb-3 text-xs font-bold uppercase tracking-[0.2em] text-accent">{copy.rulesEyebrow}</div><h2 className="text-3xl font-black tracking-tight sm:text-4xl">{copy.rulesHeading}</h2></div><dl className="divide-y divide-hairline border-y border-hairline">{copy.rules.map((rule) => <div key={rule.term} className="grid gap-2 py-5 sm:grid-cols-[11rem_1fr] sm:gap-6"><dt className="font-bold text-accent">{rule.term}</dt><dd className="max-w-2xl text-sm leading-relaxed text-text-muted">{rule.description}</dd></div>)}</dl></div></section>
  </main><Footer /></>;
}

function AssetPanel({ title, detail, href, download, buttonLabel, children }: { title: string; detail: string; href: string; download: string; buttonLabel: string; children: React.ReactNode }) {
  return <article className="flex min-h-80 flex-col rounded-[2rem] border border-hairline bg-surface p-6 shadow-[inset_0_1px_0_rgba(255,255,255,0.06)] sm:p-8"><div className="flex min-h-44 flex-1 items-center rounded-2xl border border-white/[0.06] bg-bg p-6 sm:min-h-52 sm:p-8">{children}</div><div className="mt-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h3 className="text-lg font-bold">{title}</h3><p className="mt-1 max-w-md text-sm leading-relaxed text-text-muted">{detail}</p></div><a href={href} download={download} className="inline-flex w-fit shrink-0 items-center rounded-full bg-accent px-4 py-2 text-sm font-bold text-bg transition hover:bg-accent-deep active:translate-y-px">{buttonLabel}</a></div></article>;
}
